### ISSUE TITLE
OSError: could not get source code

### ISSUE THREAD

**Issue by shantanuo** [PrefectHQ/marvin#117]
I am getting this error:

```
root@2f43e901cf78:/# python
Python 3.10.10 (main, Mar 23 2023, 14:25:51) [GCC 10.2.1 20210110] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from marvin import ai_fn
[03/31/23 08:59:34] INFO     marvin.marvin: Using OpenAI model "gpt-3.5-turbo"                                                                             logging.py:50
>>> @ai_fn
... def list_fruits(n):
...     "generate a list of n fruits"
...
>>> list_fruits(5)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.10/site-packages/marvin/bots/ai_functions.py", line 141, in ai_fn_wrapper
    function_def = inspect.cleandoc(inspect.getsource(fn))
  File "/usr/local/lib/python3.10/inspect.py", line 1139, in getsource
    lines, lnum = getsourcelines(object)
  File "/usr/local/lib/python3.10/inspect.py", line 1121, in getsourcelines
    lines, lnum = findsource(object)
  File "/usr/local/lib/python3.10/inspect.py", line 958, in findsource
    raise OSError('could not get source code')
OSError: could not get source code
```

**Comment by shantanuo** [comment]
I need to write the code in a file and run the file so that I do not get that error.
