### ISSUE TITLE
Error while opening the server.

### ISSUE THREAD

**Issue by ElCuboNegro** [PrefectHQ/marvin#181]
error on commit ba4fe3b

```
(base) PS C:\Users\jalba\Sage> marvin server start
[04/07/23 16:33:58] INFO     marvin.marvin: Using OpenAI model "gpt-3.5-turbo"                                                                                    logging.py:50
INFO:marvin.marvin:[default on default]Using OpenAI model "gpt-3.5-turbo"[/]
INFO:     Started server process [1952]
INFO:     Waiting for application startup.
INFO:     Application startup complete.
INFO:     Uvicorn running on http://127.0.0.1:4200 (Press CTRL+C to quit)
INFO:     127.0.0.1:56318 - "GET / HTTP/1.1" 307 Temporary Redirect
INFO:     127.0.0.1:56318 - "GET /docs HTTP/1.1" 200 OK
INFO:     127.0.0.1:56318 - "GET /openapi.json HTTP/1.1" 500 Internal Server Error
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "C:\Users\jalba\miniconda3\lib\site-packages\uvicorn\protocols\http\httptools_impl.py", line 436, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
  File "C:\Users\jalba\miniconda3\lib\site-packages\uvicorn\middleware\proxy_headers.py", line 78, in __call__
    return await self.app(scope, receive, send)
  File "C:\Users\jalba\miniconda3\lib\site-packages\fastapi\applications.py", line 276, in __call__
    await super().__call__(scope, receive, send)
  File "C:\Users\jalba\miniconda3\lib\site-packages\starlette\applications.py", line 122, in __call__
    await self.middleware_stack(scope, receive, send)
  File "C:\Users\jalba\miniconda3\lib\site-packages\starlette\middleware\errors.py", line 184, in __call__
    raise exc
  File "C:\Users\jalba\miniconda3\lib\site-packages\starlette\middleware\errors.py", line 162, in __call__
    await self.app(scope, receive, _send)
  File "C:\Users\jalba\miniconda3\lib\site-packages\starlette\middleware\cors.py", line 84, in __call__
    await self.app(scope, receive, send)
  File "C:\Users\jalba\miniconda3\lib\site-packages\starlette\middleware\exceptions.py", line 79, in __call__
    raise exc
  File "C:\Users\jalba\miniconda3\lib\site-packages\starlette\middleware\exceptions.py", line 68, in __call__
    await self.app(scope, receive, sender)
  File "C:\Users\jalba\miniconda3\lib\site-packages\fastapi\middleware\asyncexitstack.py", line 21, in __call__
    raise e
  File "C:\Users\jalba\miniconda3\lib\site-packages\fastapi\middleware\asyncexitstack.py", line 18, in __call__
    await self.app(scope, receive, send)
  File "C:\Users\jalba\miniconda3\lib\site-packages\starlette\routing.py", line 718, in __call__
    await route.handle(scope, receive, send)
  File "C:\Users\jalba\miniconda3\lib\site-packages\starlette\routing.py", line 276, in handle
    await self.app(scope, receive, send)
  File "C:\Users\jalba\miniconda3\lib\site-packages\starlette\routing.py", line 66, in app
    response = await func(request)
  File "C:\Users\jalba\miniconda3\lib\site-packages\fastapi\applications.py", line 231, in openapi
    return JSONResponse(self.openapi())
  File "C:\Users\jalba\miniconda3\lib\site-packages\fastapi\applications.py", line 206, in openapi
    self.openapi_schema = get_openapi(
  File "C:\Users\jalba\miniconda3\lib\site-packages\fastapi\openapi\utils.py", line 423, in get_openapi
    definitions = get_model_definitions(
  File "C:\Users\jalba\miniconda3\lib\site-packages\fastapi\utils.py", line 44, in get_model_definitions
    m_schema, m_definitions, m_nested_models = model_process_schema(
  File "pydantic\schema.py", line 581, in pydantic.schema.model_process_schema
  File "pydantic\schema.py", line 622, in pydantic.schema.model_type_schema
  File "pydantic\schema.py", line 255, in pydantic.schema.field_schema
  File "pydantic\schema.py", line 462, in pydantic.schema.field_type_schema
  File "pydantic\schema.py", line 850, in pydantic.schema.field_singleton_schema
  File "pydantic\schema.py", line 701, in pydantic.schema.field_singleton_sub_fields_schema
  File "pydantic\schema.py", line 527, in pydantic.schema.field_type_schema
  File "pydantic\schema.py", line 924, in pydantic.schema.field_singleton_schema
  File "C:\Users\jalba\miniconda3\lib\abc.py", line 123, in __subclasscheck__
    return _abc_subclasscheck(cls, subclass)
TypeError: issubclass() arg 1 must be a class
```

**Comment by jlowin** [comment]
@ElCuboNegro unfortunately I can't replicate this, can you provide more detail or debug what the `cls` is that's causing the error?

**Comment by ElCuboNegro** [comment]
I neither have any idea. we can connect and I can give you access to my computer if you want.

**Comment by ElCuboNegro** [comment]
solved on last commit.
