### ISSUE TITLE
Azure OpenAI integration: functions

### ISSUE THREAD

**Issue by TheodorosGalanos** [PrefectHQ/marvin#475]
### First check

- [X] I added a descriptive title to this issue.
- [X] I used the GitHub search to try to find a similar issue and didn't find one.
- [X] I searched the Marvin documentation for this issue.

### Bug summary

Trying to further test Azure integration with marvin's functionality. There seems to be errors when trying to use `@ai_fn`. Code and traces below.

### Reproduction

```python3
@ai_fn
def sentiment(text: str) -> float:
    """
    Given `text`, returns a number between 1 (positive) and -1 (negative)
    indicating its sentiment score.
    """


print("Text 1:", sentiment("I love working with Marvin!"))
print("Text 2:", sentiment("These examples could use some work..."))
```

### Error

```python3
Traceback (most recent call last):
  File "C:\Users\...\marvin\tests.py", line 96, in <module>
    AppRoute("update my name")
  File "C:\Program Files\Python310\lib\enum.py", line 385, in __call__
    return cls.__new__(cls, value)
  File "C:\Program Files\Python310\lib\enum.py", line 718, in __new__
    raise exc
  File "C:\Program Files\Python310\lib\enum.py", line 700, in __new__
    result = cls._missing_(value)
  File "C:\Users\...\AppData\Roaming\Python\Python310\site-packages\marvin\components\ai_classifier.py", line 67, in _missing_    
    logit_bias={
  File "C:\Users\...\AppData\Roaming\Python\Python310\site-packages\marvin\components\ai_classifier.py", line 68, in <dictcomp>   
    next(iter(model.get_tokens(str(i)))): 100
  File "C:\Users\...\AppData\Roaming\Python\Python310\site-packages\marvin\engine\language_models\base.py", line 83, in get_tokens
    enc = tiktoken.encoding_for_model(self.model)
  File "C:\Users\...\AppData\Roaming\Python\Python310\site-packages\tiktoken\model.py", line 70, in encoding_for_model
    raise KeyError(
KeyError: 'Could not automatically map openai/gpt-3.5-turbo to a tokeniser. Please use `tiktok.get_encoding` to explicitly get the tokeniser you expect.'
```

### Versions

```Text
marvin-1.0.3.dev90+gea28c9a
```

**Comment by zzstoatzz** [comment]
related to #476

**Comment by jlowin** [comment]
This was autoclosed by the PR but @TheodorosGalanos if you don't mind trying it again I'd appreciate it!

**Comment by TheodorosGalanos** [comment]
Sure, this is the current error trace after latest changes (azure_openai/...):

```python
Traceback (most recent call last):
  File "C:\Users\...\marvin\tests.py", line 76, in <module>
    print("Text 1:", sentiment("I love working with Marvin!"))
  File "C:\Users\...\Python\Python310\site-packages\marvin\components\ai_function.py", line 111, in __call__      
    output = run_sync(output)
  File "C:\Users\...\Python\Python310\site-packages\marvin\utilities\async_utils.py", line 69, in run_sync        
    return asyncio.run(coroutine)
  File "C:\Program Files\Python310\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "C:\Program Files\Python310\lib\asyncio\base_events.py", line 646, in run_until_complete
    return future.result()
  File "C:\Users\...\Python\Python310\site-packages\marvin\components\ai_function.py", line 176, in _call
    executor = OpenAIFunctionsExecutor(
  File "C:\Users\...\Python\Python310\site-packages\marvin\utilities\types.py", line 25, in __init__
    super().__init__(**data)
  File "pydantic\main.py", line 339, in pydantic.main.BaseModel.__init__
  File "pydantic\main.py", line 1066, in pydantic.main.validate_model
  File "pydantic\fields.py", line 439, in pydantic.fields.ModelField.get_default
  File "C:\Users\...\Python\Python310\site-packages\marvin\engine\language_models\base.py", line 134, in chat_llm 
    return AzureOpenAIChatLLM(model=model_name, **kwargs)
  File "pydantic\main.py", line 341, in pydantic.main.BaseModel.__init__
pydantic.error_wrappers.ValidationError: 1 validation error for AzureOpenAIChatLLM
model
  Azure OpenAI models must have the form 'azure_openai/<MODEL NAME>'. Received gpt-3.5-turbo. You can set the default model via `marvin.settings.llm_model` as a runtime setting, set the `MARVIN_LLM_MODEL` env var or pass a `model` kwarg to `AzureOpenAIChatLLM` when instantiating it. (type=value_error)
```

**Comment by TheodorosGalanos** [comment]
Works after merging with main! Thanks!
