### ISSUE TITLE
Azure OpenAI integration: classifier

### ISSUE THREAD

**Issue by TheodorosGalanos** [PrefectHQ/marvin#476]
### First check

- [X] I added a descriptive title to this issue.
- [X] I used the GitHub search to try to find a similar issue and didn't find one.
- [X] I searched the Marvin documentation for this issue.

### Bug summary

Trying to further test Azure integration with marvin's functionality. There seems to be errors when trying to use @ai_classifer. Code and traces below.

### Reproduction

```python3
@ai_classifier(model=AzureOpenAIChatLLM(max_tokens=1))
class AppRoute(Enum):
    """Represents distinct routes command bar for a different application"""

    USER_PROFILE = "/user-profile"
    SEARCH = "/search"
    NOTIFICATIONS = "/notifications"
    SETTINGS = "/settings"
    HELP = "/help"
    CHAT = "/chat"
    DOCS = "/docs"
    PROJECTS = "/projects"
    WORKSPACES = "/workspaces"


AppRoute("update my name")
```

### Error

```python3
Traceback (most recent call last):
  File "C:\Users\...\marvin\tests.py", line 96, in <module>        
    AppRoute("update my name")
  File "C:\Program Files\Python310\lib\enum.py", line 385, in __call__
    return cls.__new__(cls, value)
  File "C:\Program Files\Python310\lib\enum.py", line 718, in __new__
    raise exc
  File "C:\Program Files\Python310\lib\enum.py", line 700, in __new__
    result = cls._missing_(value)
  File "C:\Users\...\AppData\Roaming\Python\Python310\site-packages\marvin\components\ai_classifier.py", line 67, in _missing_ 
    logit_bias={
  File "C:\Users\...\AppData\Roaming\Python\Python310\site-packages\marvin\components\ai_classifier.py", line 68, in <dictcomp>
    next(iter(model.get_tokens(str(i)))): 100
  File "C:\Users\...\AppData\Roaming\Python\Python310\site-packages\marvin\engine\language_models\base.py", line 83, in get_tokens
    enc = tiktoken.encoding_for_model(self.model)
  File "C:\Users\...\AppData\Roaming\Python\Python310\site-packages\tiktoken\model.py", line 70, in encoding_for_model
    raise KeyError(
KeyError: 'Could not automatically map openai/gpt-3.5-turbo to a tokeniser. Please use `tiktok.get_encoding` to explicitly get the tokeniser you expect.'
```

### Versions

```Text
marvin-1.0.3.dev90+gea28c9a
```

**Comment by zzstoatzz** [comment]
hey @TheodorosGalanos - is your `marvin.settings.llm_model` set to `azure/gpt-35-turbo-0613`?

you should be able to pass it in like
```python
@ai_classifier(model=AzureOpenAIChatLLM(model="azure/foobar", max_tokens=1))
class AppRoute(Enum):
    """Represents distinct routes command bar for a different application"""
```

or interactively
```
❯ ipython
Python 3.11.4 | packaged by conda-forge | (main, Jun 10 2023, 18:08:41) [Clang 15.0.7 ]
Type 'copyright', 'credits' or 'license' for more information
IPython 8.14.0 -- An enhanced Interactive Python. Type '?' for help.

In [1]: from marvin.engine.language_models.azure_openai import AzureOpenAIChatLLM

In [2]: import marvin

In [3]: marvin.settings.llm_model = "azure/foobar"

In [4]: AzureOpenAIChatLLM()
Out[4]: AzureOpenAIChatLLM(name='AzureOpenAIChatLLM', model='azure/foobar', max_tokens=1500, temperature=0.0)
```

either way, we should have the default match the default for the azure settings - will look into that

**Comment by TheodorosGalanos** [comment]
Actually changing the model name to what tiktoken expects, `gpt-3.5-turbo` bypasses this error and works as expected.

**Comment by zzstoatzz** [comment]
oh nice, @TheodorosGalanos just for my understanding, where / how did you change the model name?

**Comment by TheodorosGalanos** [comment]
`marvin.settings.llm_model = gpt-3.5-turbo`

This feels like bypassing the issue, but it works.

**Comment by zzstoatzz** [comment]
the api call in `OpenAIChat` is grabbing the model to use from `marvin.settings.llm_model` by default, unless you pass it in directly to `AzureOpenAIChatLLM` like the first example above

if i were to add a validator to make it more clear

```python 
In [1]: import marvin

In [2]: marvin.settings.llm_model
Out[2]: 'openai/gpt-3.5-turbo'

In [3]: from marvin.engine.language_models.azure_openai import AzureOpenAIChatLLM

In [4]: AzureOpenAIChatLLM()
---------------------------------------------------------------------------
ValidationError                           Traceback (most recent call last)
Cell In[4], line 1
----> 1 AzureOpenAIChatLLM()

File ~/micromamba/envs/marvin/lib/python3.11/site-packages/pydantic/main.py:341, in pydantic.main.BaseModel.__init__()

ValidationError: 1 validation error for AzureOpenAIChatLLM
model
  Azure OpenAI models must have the form 'azure/<MODEL NAME>'. Received openai/gpt-3.5-turbo. You can set the default model via `marvin.settings.llm_model` as a runtime setting, set the `MARVIN_LLM_MODEL` env var or pass a `model` kwarg to `AzureOpenAIChatLLM` when instantiating it. (type=value_error)
  ```
  
  how does that sound? or would there be way you'd prefer to set this up

**Comment by TheodorosGalanos** [comment]
Yeah that looks good. Is the `azure/` pattern from marvin or actually azure? I don't think I've every noticed that before.

Other than that, looks good!

**Comment by zzstoatzz** [comment]
its from marvin! now that we're supporting openai, azure openai, and anthropic, we've needed a way to differentiate the providers and their models

feel free to let us know if there's a way that'd feel more convenient though 😄

**Comment by TheodorosGalanos** [comment]
yep that's good! As long as it's consistent I'm fine with it :)

Is that pushed right now on main, can I try it? I get an error when I do but I haven't pulled in a while.

**Comment by zzstoatzz** [comment]
cool!

i added an azure model as the default for `AzureOpenAIChatLLM` now so it should use it even with the default openai setting

```python
In [1]: import marvin

In [2]: marvin.settings.llm_model
Out[2]: 'openai/gpt-3.5-turbo'

In [3]: marvin.settings.azure_openai.llm_model
Out[3]: 'azure/gpt-35-turbo-0613'

In [4]: from marvin.engine.language_models.azure_openai import AzureOpenAIChatLLM

In [5]: AzureOpenAIChatLLM()
Out[5]: AzureOpenAIChatLLM(name='AzureOpenAIChatLLM', model='azure/gpt-35-turbo-0613', max_tokens=1500, temperature=0.0)
```

this is pushed to the [`hotfix/azure`](https://github.com/PrefectHQ/marvin/tree/hotfix/azure) branch - will get merged sometime tomorrow I'm sure!

**Comment by TheodorosGalanos** [comment]
Awesome, this looks good! I am ok to close the issue when you are.

**Comment by jlowin** [comment]
This was autoclosed by the PR but @TheodorosGalanos if you don't mind trying it again I'd appreciate it!

**Comment by TheodorosGalanos** [comment]
Works now, after updating to main!

**Comment by jlowin** [comment]
Thanks!
