### ISSUE TITLE
Azure OpenAI integration: AI Application

### ISSUE THREAD

**Issue by TheodorosGalanos** [PrefectHQ/marvin#477]
### First check

- [X] I added a descriptive title to this issue.
- [X] I used the GitHub search to try to find a similar issue and didn't find one.
- [X] I searched the Marvin documentation for this issue.

### Bug summary

Trying to further test Azure integration with marvin's functionality. There seems to be errors when trying to use `AIApplication`. Code and traces below.

### Reproduction

```python3
# create models to represent the state of our ToDo app
class ToDo(BaseModel):
    title: str
    description: str = None
    due_date: datetime = None
    done: bool = False


class ToDoState(BaseModel):
    todos: list[ToDo] = []


# create the app with an initial state and description
todo_app = AIApplication(
    state=ToDoState(),
    description=(
        "A simple todo app. Users will provide instructions for creating and updating"
        " their todo lists."
    ),
)

# invoke the application by adding a todo
response = todo_app("I need to go to the store tomorrow at 5pm")


print(
    f"Response: {response.content}\n",
)
print(f"App state: {todo_app.state.json(indent=2)}")
```

### Error

```python3
File "C:\Users\...\marvin\tests.py", line 61, in <module>        
    response = todo_app("I need to go to the store tomorrow at 5pm")
  File "C:\Users\...\AppData\Roaming\Python\Python310\site-packages\marvin\components\ai_application.py", line 255, in __call__
    return run_sync(self.run(input_text=input_text, model=model))
  File "C:\Users\...\AppData\Roaming\Python\Python310\site-packages\marvin\utilities\async_utils.py", line 69, in run_sync     
    return asyncio.run(coroutine)
  File "C:\Program Files\Python310\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "C:\Program Files\Python310\lib\asyncio\base_events.py", line 646, in run_until_complete
    return future.result()
  File "C:\Users\...\AppData\Roaming\Python\Python310\site-packages\marvin\components\ai_application.py", line 302, in run     
    responses = await executor.start(
  File "C:\Users\...\AppData\Roaming\Python\Python310\site-packages\marvin\engine\executors\base.py", line 34, in start        
    response = await self.step(messages)
  File "C:\Users\...\AppData\Roaming\Python\Python310\site-packages\marvin\engine\executors\base.py", line 45, in step
    llm_response = await self.run_engine(messages=messages)
  File "C:\Users\...\AppData\Roaming\Python\Python310\site-packages\marvin\engine\executors\openai.py", line 63, in run_engine
    llm_response = await self.model.run(
  File "C:\Users\...\AppData\Roaming\Python\Python310\site-packages\marvin\engine\language_models\openai.py", line 146, in run
    openai_kwargs = self._get_openai_settings()
  File "C:\Users\...\AppData\Roaming\Python\Python310\site-packages\marvin\engine\language_models\openai.py", line 87, in _get_openai_settings 
    raise ValueError(
ValueError: OpenAI API key not set. Please set it or use the MARVIN_OPENAI_API_KEY environment variable.
```

### Versions

```Text
marvin-1.0.3.dev90+gea28c9a
```

**Comment by TheodorosGalanos** [comment]
Alright running it from this now gives the following error:

```python
Traceback (most recent call last):
  File "C:\Users\...\marvin\tests.py", line 59, in <module>
    response = todo_app("I need to go to the store tomorrow at 5pm")
  File "C:\Users\...\components\ai_application.py", line 255, in __call__   
    return run_sync(self.run(input_text=input_text, model=model))
  File "C:\Users\...\Python\Python310\site-packages\marvin\utilities\async_utils.py", line 69, in run_sync        
    return asyncio.run(coroutine)
  File "C:\Program Files\Python310\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "C:\Program Files\Python310\lib\asyncio\base_events.py", line 646, in run_until_complete
    return future.result()
  File "C:\Users\...\Python\Python310\site-packages\marvin\components\ai_application.py", line 265, in run        
    model = chat_llm()
  File "C:\Users\...\Python\Python310\site-packages\marvin\engine\language_models\base.py", line 136, in chat_llm 
    raise ValueError(f"Unknown provider / model: {model}")
ValueError: Unknown provider / model: azure/gpt-3.5-turbo
```

**Comment by zzstoatzz** [comment]
ah my fault 🙄  got confused, i should have recommended `azure_openai/` as the syntax, sorry about that! default setting changed and pushed to hotfix/azure

**Comment by TheodorosGalanos** [comment]
Just a heads up, this seems to re-surface the tiktoken error again. 

`azure_openai/gpt-3.5-turbo-6301` is not a valid identifier and thus gives the following error: 

`KeyError: 'Could not automatically map azure_openai/gpt-35-turbo-0613 to a tokeniser. Please use `tiktok.get_encoding` to explicitly get the tokeniser you expect.'` (notice it takes the `.` away from the name as well).

**Comment by zzstoatzz** [comment]
we've just merged a change to `main` that simplifies things a bit, `AzureOpenAIChat` will just have `azure_openai/gpt-35-turbo` as a default, unless you pass a `model` otherwise

and we're now using the regular 3.5 tokenizer as a fallback, so if you try installing main, this should work for you ! let us know if not

**Comment by TheodorosGalanos** [comment]
Alright testing main now!

**Comment by TheodorosGalanos** [comment]
After pulling main, we now get an api key error. Might be it's trying to use openai again? Or is the MARVIN variable needed?

`ValueError: OpenAI API key not set. Please set it or use the MARVIN_OPENAI_API_KEY environment variable.`

**Comment by jlowin** [comment]
I can replicate this -- the model is not being passed to the functions executor so its inventing a default.
