### ISSUE TITLE
Calling `.generate` gives error `RuntimeWarning: coroutine 'AIModel._get_arguments' was never awaited`

### ISSUE THREAD

**Issue by lmmx** [PrefectHQ/marvin#511]
### First check

- [X] I added a descriptive title to this issue.
- [X] I used the GitHub search to try to find a similar issue and didn't find one.
- [X] I searched the Marvin documentation for this issue.

### Bug summary

Calling `.generate()` on an AI model (generated using the decorator on a Pydantic model in the documented way) did not work. The `.extract()` method worked OK.

### Reproduction

```python3
from marvin import ai_model, settings
from pydantic import BaseModel, Field

settings.llm_model = "gpt-3.5-turbo"


@ai_model
class PersonalInfo(BaseModel):
    first_name: str
    last_name: str
    homepage: str
    phone_number: str = Field(None, description="dash-delimited phone number")
    postcode: str = Field(None, description="UK postcode")


some_guy = PersonalInfo.generate("Just some guy")
```

### Error

```python3
Traceback (most recent call last):
  File "/home/louis/dev/testing/marvin/entity_extraction/main.py", line 16, in <module>
    some_guy = PersonalInfo.generate("Just some guy")
  File "/home/louis/miniconda3/envs/marvin/lib/python3.10/site-packages/marvin/components/ai_model.py", line 177, in generate
    arguments.update(kwargs)
AttributeError: 'coroutine' object has no attribute 'update'
```

### Versions

It's version 1.2.1

It says there is no such command `marvin version`:

```
Usage: marvin [OPTIONS] COMMAND [ARGS]...
Try 'marvin --help' for help.
╭─ Error ────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────╮
│ No such command 'version'.                                                                                                                     │
╰────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯
```

### Additional context

When I exit the interpreter I get a warning

```
sys:1: RuntimeWarning: coroutine 'AIModel._get_arguments' was never awaited
```

When I breakpoint at line 177 of `marvin.components.ai_model` I see `arguments` is (obviously) a coroutine, when it should be a dict.

There should be an `await` here:

https://github.com/PrefectHQ/marvin/blob/22274c68e85e6062ba7d7e7cead1343bad4a3808/src/marvin/components/ai_model.py#L174

like there is for the `.extract()` internal method `._extract_async()` here:

https://github.com/PrefectHQ/marvin/blob/22274c68e85e6062ba7d7e7cead1343bad4a3808/src/marvin/components/ai_model.py#L145

**Comment by lmmx** [comment]
No problem Adam, happy to help :smile: 

My outlined fix above was too simple: `await` must be in an async funcdef, called with the `run_sync()` helper as done for `extract`. Just fixed in my fork, will send a PR now.

Tried a few runs and got the same result irregardless of the prompt... :thinking:
