### ISSUE TITLE
Can't set model with ai_classifier decorator

### ISSUE THREAD

**Issue by nejko** [PrefectHQ/marvin#599]
### First check

- [X] I added a descriptive title to this issue.
- [X] I used the GitHub search to try to find a similar issue and didn't find one.
- [X] I searched the Marvin documentation for this issue.

### Bug summary

If I try to set a model using `@ai_classifier` decorator, I get a TypeError.

### Reproduction

```python3
@ai_classifier(model="openai/gpt-4")
class DealStatus(Enum):
    f"""
    <my instructions for classification>
    """

    NOT_A_PROSPECT = 1
    DEAL_OPEN = 2
    DEAL_CLOSED_WON = 3
```

### Error

```python3
(sell) nejc@Nejcs-MBP-2 sell % python engine.py
Traceback (most recent call last):
  File "/Users/nejc/Desktop/Dev/sell/engine.py", line 2, in <module>
    from tools import create_deal, get_threads_between_dates, extract_external_domains
  File "/Users/nejc/Desktop/Dev/sell/tools.py", line 7, in <module>
    from classes import DealStatus, ParsedDeal, Deal, ParsedTask, Task, EmailMessage, EmailThread
  File "/Users/nejc/Desktop/Dev/sell/classes.py", line 39, in <module>
    class DealStatus(Enum):
  File "/Users/nejc/Desktop/Dev/sell/lib/python3.9/site-packages/marvin/components/ai_classifier.py", line 299, in decorator
    model=model(**model_kwargs),
TypeError: 'str' object is not callable
```

### Versions

```Text
1.5.0
```

**Comment by nejko** [comment]
Open by mistake, sorry.
