### ISSUE TITLE
Documentation for drop-in OpenAI replacement does not work

### ISSUE THREAD

**Issue by teedrupp** [PrefectHQ/marvin#633]
### First check

- [X] I added a descriptive title to this issue.
- [X] I used the GitHub search to try to find a similar issue and didn't find one.
- [X] I searched the Marvin documentation for this issue.

### Bug summary

The documentation here
* https://github.com/PrefectHQ/marvin/blob/main/docs/utilities/chat_completion.md?plain=1#L92

states that

```
ChatCompletion is designed to be a drop-in replacement for OpenAI's ChatCompletion.
Just import openai from marvin or, equivalently, ChatCompletion from marvin.openai.
```

However, when using the example provided, it produces this following error.

```
$ python scratch.py
Traceback (most recent call last):
  File "/home/tim/scratch.py", line 4, in <module>
    openai.ChatCompletion.create(
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'function' object has no attribute 'create'
```

Changing the call to `openai.ChatCompletion().create` causes the error to go away, but a different error arises; the script just blocks indefinitely.

```
^CTraceback (most recent call last):
  File "/home/tim/.pyenv/versions/test1/lib/python3.11/site-packages/marvin/utilities/async_utils.py", line 61, in run_sync
    loop = asyncio.get_running_loop()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: no running event loop

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/tim/.pyenv/versions/3.11.3/lib/python3.11/asyncio/runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/tim/.pyenv/versions/3.11.3/lib/python3.11/asyncio/base_events.py", line 653, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/home/tim/.pyenv/versions/test1/lib/python3.11/site-packages/marvin/core/ChatCompletion/providers/openai.py", line 211, in _send_request_async
    response = await openai.ChatCompletion.acreate(**serialized_request)  # type: ignore # noqa
```

Interesting that its making mention of `acreate`, because I made no mention to `acreate` in my copying of the example from the documentatio.

### Reproduction

```python3
from marvin import openai
openai.ChatCompletion.create(
    messages = [{
        'role': 'user',
        'content': 'Hey! How are you?'
    }]
)
```

### Error

```python3
Traceback (most recent call last):
  File "/home/tim/scratch.py", line 4, in <module>
    openai.ChatCompletion.create(
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'function' object has no attribute 'create'
```

### Versions

```Text
Version:                1.5.5
Python version:         3.11.3
OS/Arch:                linux/x86_64
```

**Comment by teedrupp** [comment]
note that changing the example to be the following makes it work

```
openai.ChatCompletion('gpt-3.5-turbo').create(
    messages = [{
        'role': 'user',
        'content': 'Hey! How are you?'
    }]
)
```

but this is not a drop-in replacement, as the stock `openai` module, pre 1.0, does not define ChatCompletion as a function. Post 1.0 there are numerous changes to the `openai` module, so I'm excluding those differences here

**Comment by zzstoatzz** [comment]
hi @teedrupp - thanks for the issue. this is true, we should either update the language or the behavior.

i've got a draft PR (#618) to make the classmethods work, but I'm sure @aaazzam will have some thoughts here on the exact implementation.

**Comment by teedrupp** [comment]
thanks. wasn't aware that there was a PR in draft.
