### ISSUE TITLE
argument after ** must be a mapping, not str

### ISSUE THREAD

**Issue by tekumara** [PrefectHQ/marvin#656]
### First check

- [X] I added a descriptive title to this issue.
- [X] I used the GitHub search to try to find a similar issue and didn't find one.
- [X] I searched the Marvin documentation for this issue.

### Bug summary

`argument` to function call is the string `'{"x": 4124124, "y": 48124}'` but should be a dict

### Reproduction

```python3
from marvin import openai
from marvin.utilities.messages import Message, Role

#openai.api_key = "secret_key"


def divide(x: float, y: float) -> str:
    """Divides x and y"""
    return str(x / y)


def add(x: int, y: int) -> str:
    """Adds x and y"""
    return str(x + y)


with openai.ChatCompletion('claude-2', functions=[add, divide]) as conversation:
    # Start off with an external question / prompt.
    prompt = "What is 4124124 + 424242 divided by 48124?"

    # Initialize the conversation with a prompt from the user.
    conversation.send(messages=[Message(role=Role.USER, content=prompt)])

    # While the most recent turn has a function call, evaluate it.
    while conversation.last_turn.has_function_call():
        # Send the most recent function call to the conversation.
        messages = conversation.last_turn.call_function()
        conversation.send(messages=messages if isinstance(messages, list) else [messages])
```

### Error

```python3
[11/23/23 21:39:25] DEBUG    marvin.ChatCompletion.handlers: Function call: Calling function 'divide' with      logging.py:65
                             payload: "{\"x\": 4124124, \"y\": 48124}"                                                       
Traceback (most recent call last):
  File "/opt/homebrew/Cellar/python@3.10/3.10.13_1/Frameworks/Python.framework/Versions/3.10/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/opt/homebrew/Cellar/python@3.10/3.10.13_1/Frameworks/Python.framework/Versions/3.10/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/Users/tekumara/marvin-demo/marvindemo/chaining.py", line 27, in <module>
    messages = conversation.last_turn.call_function()
  File "/Users/tekumara/marvin-demo/.venv/lib/python3.10/site-packages/marvin/core/ChatCompletion/handlers.py", line 168, in call_function
    function_result = function_registry[name](**argument)
TypeError: __main__.divide() argument after ** must be a mapping, not str
```

### Versions

```Text
❯ marvin version
Version:                1.5.6
Python version:         3.10.13
OS/Arch:                darwin/arm64
```

### Additional context

Using claude 2

**Comment by zzstoatzz** [comment]
hi @tekumara - thanks for the issue! unfortunately we are not supporting claude at this time - feel free to reach out if you have any questions about marvin 2 features / bugs!
