### ISSUE TITLE
Azure OpenAI doesn't work with `.env` in project-specific directories

### ISSUE THREAD

**Issue by lostmygithubaccount** [PrefectHQ/marvin#766]
### First check

- [X] I added a descriptive title to this issue.
- [X] I used the GitHub search to try to find a similar issue and didn't find one.
- [X] I searched the Marvin documentation for this issue.

### Bug summary

per https://github.com/PrefectHQ/marvin/blob/main/cookbook/azure/README.md and https://www.askmarvin.ai/docs/configuration/settings/, you should just need to set the environment variables. I've done this in `ibis-birdbrain/.env` and used `python-dotenv` to load them in, but they don't seem to work

instead placing the same `.env` file in `~/.marvin/.env` works

per the current documentation, I'd expect the former to still work. the motive behind this instead of global settings is to be able to set it differently for different projects/bots 

### Reproduction

```python3
above
```

### Error

```python3
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
Cell In[8], line 1
----> 1 result = marvin.classify(
      2     "Marvin is so easy to use!",
      3     labels=["positive", "negative"],
      4 )

File ~/repos/ibis-birdbrain/venv/lib/python3.11/site-packages/marvin/ai/text.py:350, in classify(data, labels, instructions, model_kwargs, client)
    328 """
    329 Classifies the provided data based on the provided labels.
    330 
   (...)
    346     T: The label that the data was classified into.
    347 """
    349 model_kwargs = model_kwargs or {}
--> 350 return _generate_typed_llm_response_with_logit_bias(
    351     prompt_template=CLASSIFY_PROMPT,
    352     prompt_kwargs=dict(data=data, labels=labels, instructions=instructions),
    353     model_kwargs=model_kwargs | dict(temperature=0),
    354     client=client,
    355 )

File ~/repos/ibis-birdbrain/venv/lib/python3.11/site-packages/marvin/ai/text.py:209, in _generate_typed_llm_response_with_logit_bias(prompt_template, prompt_kwargs, encoder, max_tokens, model_kwargs, client)
    205 grammar = cast_labels_to_grammar(
    206     labels=label_strings, encoder=encoder, max_tokens=max_tokens
    207 )
    208 model_kwargs.update(grammar.model_dump())
--> 209 response = generate_llm_response(
    210     prompt_template=prompt_template,
    211     prompt_kwargs=(prompt_kwargs or {}) | dict(labels=label_strings),
    212     model_kwargs=model_kwargs | dict(temperature=0),
    213     client=client,
    214 )
    216 # the response contains a single number representing the index of the chosen
    217 label_index = int(response.response.choices[0].message.content)

File ~/repos/ibis-birdbrain/venv/lib/python3.11/site-packages/marvin/ai/text.py:79, in generate_llm_response(prompt_template, prompt_kwargs, model_kwargs, client)
     59 def generate_llm_response(
     60     prompt_template: str,
     61     prompt_kwargs: Optional[dict] = None,
     62     model_kwargs: Optional[dict] = None,
     63     client: Optional[MarvinClient] = None,
     64 ) -> ChatResponse:
     65     """
     66     Generates a language model response based on a provided prompt template.
     67 
   (...)
     77         ChatResponse: The generated response from the language model.
     78     """
---> 79     client = client or MarvinClient()
     80     model_kwargs = model_kwargs or {}
     81     prompt_kwargs = prompt_kwargs or {}

    [... skipping hidden 1 frame]

File ~/repos/ibis-birdbrain/venv/lib/python3.11/site-packages/marvin/client/openai.py:204, in MarvinClient.<lambda>()
    199 class MarvinClient(pydantic.BaseModel):
    200     model_config = pydantic.ConfigDict(
    201         arbitrary_types_allowed=True, protected_namespaces=()
    202     )
--> 204     client: Client = pydantic.Field(default_factory=lambda: _get_default_client("sync"))
    206     @classmethod
    207     def wrap(cls, client: Client) -> "Client":
    208         client.chat.completions.create = partial(
    209             cls(client=client).generate_chat, completion=client.chat.completions.create
    210         )  # type: ignore #noqa

File ~/repos/ibis-birdbrain/venv/lib/python3.11/site-packages/marvin/client/openai.py:179, in _get_default_client(client_type)
    175 api_key = (
    176     settings.openai.api_key.get_secret_value() if settings.openai.api_key else None
    177 )
    178 if not api_key:
--> 179     raise ValueError(
    180         inspect.cleandoc(
    181             """
    182         OpenAI API key not found! Marvin will not work properly without it.
    183         
    184         You can either:
    185             1. Set the `MARVIN_OPENAI_API_KEY` or `OPENAI_API_KEY` environment variables
    186             2. Set `marvin.settings.openai.api_key` in your code (not recommended for production)
    187             
    188         If you do not have an OpenAI API key, you can create one at https://platform.openai.com/api-keys.
    189         """
    190         )
    191     )
    192 if client_type not in ["sync", "async"]:
    193     raise ValueError(f"Invalid client type {client_type!r}")

ValueError: OpenAI API key not found! Marvin will not work properly without it.

You can either:
    1. Set the `MARVIN_OPENAI_API_KEY` or `OPENAI_API_KEY` environment variables
    2. Set `marvin.settings.openai.api_key` in your code (not recommended for production)
    
If you do not have an OpenAI API key, you can create one at https://platform.openai.com/api-keys.
```

### Versions

```Text
installed from main

marvin version is leading to:

Traceback (most recent call last):
  File "/Users/cody/.local/share/rtx/installs/python/latest/bin/marvin", line 5, in <module>
    from marvin.cli import app
  File "/Users/cody/.local/share/rtx/installs/python/3.11.5/lib/python3.11/site-packages/marvin/__init__.py", line 3, in <module>
    from .ai.text import fn, cast, extract, classify, classifier, generate, model, Model
  File "/Users/cody/.local/share/rtx/installs/python/3.11.5/lib/python3.11/site-packages/marvin/ai/__init__.py", line 2, in <module>
    from . import audio
  File "/Users/cody/.local/share/rtx/installs/python/3.11.5/lib/python3.11/site-packages/marvin/ai/audio.py", line 4, in <module>
    from openai._base_client import HttpxBinaryResponseContent
ImportError: cannot import name 'HttpxBinaryResponseContent' from 'openai._base_client' (/Users/cody/.local/share/rtx/installs/python/3.11.5/lib/python3.11/site-packages/openai/_base_client.py)
```

**Comment by zzstoatzz** [comment]
hi @lostmygithubaccount - thanks for the issue, support for local dotenv files should be added [here](https://github.com/PrefectHQ/marvin/pull/771)
